fix: added flutter clean, updated dependencies and checks of generated package

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,7 +49,9 @@ jobs:
         run: ls .dart_tool/
 
       - name: Get dependencies
-        run: flutter pub get
+        run: |
+          flutter clean
+          flutter pub get
       - name: check contents of .dart_tool directory before builder
         run: ls .dart_tool/flutter_gen/gen_l10n/
       - name: Run build runner
@@ -60,6 +62,13 @@ jobs:
       
       - name: check contents of .dart_tool directory after builder
         run: ls .dart_tool/flutter_gen/gen_l10n/
+      
+      - name: checking gen_l10n directory
+        run: |
+          echo "Checking .dart_tool/flutter_gen/gen_l10n directory:" 
+          ls -la .dart_tool/flutter_gen/gen_l10n || echo "Directory not found"
+
+
       
       - name: Compile a bundle
         run: flutter build appbundle
